spring:
  application:
    name: kitchen-admin
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/kitchen
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  # Exposed Configuration
  exposed:
    generate-ddl: false
  
  # Security Configuration
  security:
    user:
      name: admin
      password: admin

# Server Configuration
server:
  port: 8080

# Swagger UI / OpenAPI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /api-docs