spring:
  application:
    name: kitchen-admin

  # Database Configuration
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/kitchen}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PWD:postgres}
    driver-class-name: org.postgresql.Driver

  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  # Exposed Configuration
  exposed:
    generate-ddl: false

  # Security Configuration
  security:
    user:
      name: ${ADMIN_NAME:admin}
      password: ${ADMIN_PWD:admin}

notification:
  token: ${NOTIFICATION_TOKEN:adminadminadmin}
# Server Configuration
server:
  port: 8080

# Swagger UI / OpenAPI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /api-docs

# Logging Configuration
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
